### ISSUE TITLE
Balancing! Rat is usually too OP in Cool World and beyond

### ISSUE THREAD

**Issue by airbreather** [airbreather/Autopelago#51]
I want to be able to push a button, then have a run of 4 players at once go to completion as quickly as possible, then get some sort of machine-readable output of exactly what happened and when (timing based on how many game steps had passed).

I need to know this in order to be able to analyze and tune and balance the numbers. It would be extremely helpful to see the real-world impact of, say, changing the DC values on certain checks.

**Comment by skidznet** [comment]
In addition to data collection for balancing, it is useful to track how many times rat chat types are triggered
