### ISSUE TITLE
Show where the rat is moving

### ISSUE THREAD

**Issue by SnolidIce** [airbreather/Autopelago#78]
Sometimes the rat's movement is confusing and having the dots light up to see where the rat is moving can help with some visual clarity

**Comment by ironminer888** [comment]
Seconding this! I just played around a bit with the software and think it has potential to be very fun as a companion to an AP run. Right now the rat can be a bit hard to track, maybe you could place a marker on where he's trying to go? Technically you can hover over the rat to see its next priority, but it'd be a nice bit of convenience just to see it at a glance.

I'd also like to have the "Before Major Location" locations change somehow after they've been checked, something like how PopTracker changes location colors?
