### ISSUE TITLE
Add item and location groups!

### ISSUE THREAD

**Issue by ladybunne** [airbreather/Autopelago#91]
Hello! I think it'd be helpful to have item and location groups added to the apworld, as it'd give players a bit more control over how to interact with hints and such.

I'm struggling to find documentation for this feature, but you can see examples of it in [the datapackage](https://archipelago.gg/datapackage) - each game has some mappings of strings to arrays of item and location names.

We discussed in the game thread that an item group for "rats" would be useful for the checks that need lots of rats, but otherwise I'm not too sure what else would be suitable. Happy to defer to world designer direction here!

**Comment by airbreather** [comment]
Coming up:
![image](https://github.com/user-attachments/assets/677f09c6-b574-4bde-8030-8fc5131813cd)
